# Generated by Django 2.2.1 on 2019-06-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
                ('clean_layer', models.CharField(max_length=500)),
                ('spd_tol', models.IntegerField()),
                ('buffr', models.IntegerField()),
                ('n_freq', models.IntegerField()),
                ('n_points', models.IntegerField()),
                ('d_gps', models.FileField(blank=True, upload_to='uploads/%Y_%m_%d/')),
                ('d_res', models.FileField(blank=True, upload_to='uploads/%Y_%m_%d/')),
            ],
        ),
    ]
