# Generated by Django 2.2.1 on 2019-06-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_vial_layer', models.CharField(max_length=500)),
                ('GPS_layer', models.CharField(max_length=500)),
                ('gbd', models.FileField(upload_to='uploads/%Y_%M_%d/')),
                ('description', models.TextField(default='')),
                ('gbd_root', models.CharField(max_length=500)),
                ('metrica', models.CharField(max_length=500)),
            ],
        ),
    ]
