# Generated by Django 2.2.1 on 2019-05-30 23:57

from django.db import migrations, models
import input.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.FileField(upload_to=input.models.input_directory_path)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
